site_name: Proofixel
site_url: https://blog.proofixel.com
site_author: Proofixel Team
copyright: |
  <span class="meu-copyright">Copyright &copy; 2026 <a href="https://proofixel.com" target="_blank" rel="noopener">PROOFIXEL</a></span>

theme:
  name: material
  language: pt-BR
  logo: assets/logo.png
  favicon: assets/favicon.ico
  palette: 
    # Modo Claro (Opcional, caso o usuário troque)
    - scheme: default
      primary: white
      accent: deep purple
      toggle:
        icon: material/brightness-7
        name: Mudar para modo claro
    
    # Modo Escuro (O PROOFIXEL MODE)
    - scheme: slate
      primary: custom # Isso avisa o MkDocs: "Deixa que eu resolvo no CSS"
      accent: deep purple
      toggle:
        icon: material/brightness-4
        name: Mudar para modo escuro
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.top
    - search.suggest
    - search.highlight
    # IMPORTANTE: Recursos específicos de Blog
    - navigation.indexes 
    - header.autohide
    - navigation.tabs
    - navigation.sections
plugins:
  - search
  - blog:
      post_dir: posts         # Pasta onde ficam os textos
      post_date_format: full  # Formato da data
      authors_file: "{blog}/.authors.yml" # Arquivo com info dos autores

extra_css:
  - assets/custom.css      
  - stylesheets/extra.css

markdown_extensions:
  - admonition
  - footnotes
  - attr_list
  - def_list
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - md_in_html              

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - assets/mathjax.js
  - assets/mermaid-init.js

nav:
  - Research Log: index.md  # A Home que acabamos de criar
  - Labs:          # O agrupador no menu esquerdo
    - 'A Ciência dos Pixels': blog/a-ciencia-dos-pixels.md
    - 'Popper no Sofware, um Erro que da Certo': blog/Popper_no_Software_e_na_A.I.md

     

